### ISSUE TITLE
[RFC0025] Pipeline to automate collection update

### ISSUE THREAD

**Issue by jungtop** [OpenPecha/Pipeline-to-automate-collection-update#1]
## Work Planning

<details>
  <summary>Details</summary>

<h2 id="table-of-contents">Table of Contents</h2>

- [Housekeeping](#housekeeping)
- [Named Concepts](#named-concepts)
- [Summary](#summary)
- [Reference-Level Explanation](#reference-level-explanation)
- [Alternatives](#alternatives)
  * [Rationale](#rationale)
- [Drawbacks](#drawbacks)
- [Useful References](#useful-references)
- [Unresolved questions](#unresolved-questions)
- [Parts of the system affected](#parts-of-the-system-affected)
- [Future possibilities](#future-possibilities)
- [Infrastructure](#infrastructure)
- [Testing](#testing)
- [Documentation](#documentation)
- [Version History](#version-history)
- [Recordings](#recordings)
- [Work Phases](#work-phases)

<h2 id="housekeeping">Housekeeping</h2>

*Please add ref in specified format into `RFC` title, e.g `[RFC9999]` if corresponding RFW is `[RFW9999]`.*

*Please add into this `RFC` and related `PR's` titles `[RFC_id]` e.g `[RFC_9999]`.*

ALL BELOW FIELDS ARE REQUIRED

<h2 id="named-concepts">Named Concepts</h2>

**Collection** : Collection in openpecha can be collection of opfs(pecha), opa(alignment) and collection.
**Github Action** : continuous integration and continuous delivery (CI/CD) platform that allows you to automate your build, test, and deployment pipeline.

<h2 id="summary">Summary</h2>

A  pipeline which automatically updates collection's view when associated opfs has been updated.

<h2 id="reference-level-explanation">Reference-Level Explanation</h2>

An github action of the collection will listen to the source opfs in a definite interval of time.
If there is any commits between the two intervals,new view is created and push to the corresponding collection.

<h2 id="alternatives">Alternatives</h2>

Instead of listening to the changes from the collection repo gtihub action to source opfs,action from the source opfs can be triggered by commit and views are recreated. 

<h3 id="rationale">Rationale</h3>

<em>
- Why the currently proposed design was selected over alternatives?
</em>

Since the collection are created after opfs, it is not possible to include the target collection in the action of the source opfs.

<em>
- What would be the impact of going with one of the alternative approaches?
</em>

There will be less resource utilization for the alternative approach as the action is only triggered when there is changes, while 
for the chosen approach the action is triggered in every interval of time.

<h2 id="drawbacks">Drawbacks</h2>

*Describe any particular caveats and drawbacks that may arise from fulfilling this particular request?*

<h2 id="useful-rererences">Useful References</h2>

*Describe useful parallels and learnings from other requests, or work in previous projects.*

<em>
  
- What similar work have we already successfully completed?:None
- Is this something that have already been built by others?:None
- What other related learnings we have?:Github Action
- Are there useful academic literature or other articles related with this topic? (provide links):None
- Have we built a relevant prototype previously?:No
- Do we have a rough mock for the UI/UX?:No
- Do we have a schematic for the system?:No

</em>

<h2 id="unresolved-questions">Unresolved Questions</h2>

<em>

- What is there that is unresolved (and will be resolved as part of fulfilling this request)?
- Are there other requests with same or similar problems to solve?:No
  
</em>

<h2 id="parts-of-the-system-affected">Parts of the System Affected</h2>

<em>

- Which parts of the current system are affected by this request?:None
- What other open requests are closely related with this request?:None
- Does this request depend on fulfillment of any other request?:No
- Does any other request depend on the fulfillment of this request?:No

</em>
 
<h2 id="future-possibilities">Future possibilities</h2>

*How do you see the particular system or part of the system affected by this request be altered or extended in the future.*

<h2 id="infrastructure">Infrastructure</h2>

- Github Action to do the automation.
- Openpecha to create the views.

<h2 id="testing">Testing</h2>

The testing procedure can be done in the following steps:

- Check if the action runs on specific time interval.
- Check whether the action catches the commit made in the source opfs in last interval.
- Test whether the new views are pushed in the collection repository.

<h2 id="documentation">Documentation</h2>

- Developer Documentation
   - Embedding the action in the collection

<h2 id="version-history">Version History</h2>

v 0.0.1

<h2 id="recordings">Recordings</h2>

*Links to audio recordings of related discussion.*

</details>

 
<h2 id="work-phases">Work Phases</h2>

<h3 id="non-coding">Planning</h3>

*Keep original naming and structure, and keep as first section in Work phases section*

- [ ] RFC completed on: 9th Febuary,2023
      Estimated time: 
      Actual time: 
- [ ] RFC reviewed and approved by: 
      Estimated time: 
      Actual time: 

<h3 id="implementation">Implementation</h3>

- [ ] #2
      Estimated time: 4 hours
      Actual time: 
- [ ] #3
      Estimated time: 2 hours
      Actual time: 
- [ ] #4
      Estimated time:  4 hours
      Actual time: 
- [ ] #5
      Estimated time: 4 hours
      Actual time: 
- [ ] #6
      Estimated time: 4 hours
      Actual time: 

<h3 id="implementation">Completion</h3>

- [ ] Tested and approved by: @username, @username
      Estimated time: 
      Actual time: 
- [ ] Documentation approved @evanyerburgh
      Estimated time: 
      Actual time:

**Comment by kaldan007** [comment]
@jungtop  in case of pecha collection i don't see any issue with current workflow. But when it comes to alignment collections,  i think we need to keep our alignment files synced with associated opfs and we can then listen to updates in alignment files and trigger the view updates. As despite knowing changes in opfs, if our alignments are not updated we can't serialise the views.

**Comment by jungtop** [comment]
@kaldan007 oh it is right,for opa the action should listen to the changes in the opa.Also there should be another github action for opa which updates the opa when there is a change in the source opfs of opa.
